### ISSUE TITLE
Add Proxy port filtering

### ISSUE THREAD

**Issue by Miiraak** [m-henderson/ProxySharp#14]
Adding a port filtering feature can be useful in many situations.  

- `Flexibility` : Adapt the proxy to specific network environments, including those where certain ports are `blocked` or `reserved`.
- `Compatibility` : Some environments or applications may require the use of `specific ports` for compatibility reasons.
- `Security` : Using non-standard ports can make the proxy `more discreet`, which can be a little security advantage.
- `Conflicts` : Some users may need to `avoid conflicts` with other services that already use standard ports on their system.

For that, we can use the already implemented proxies scraping and queuing, coping the function for countries filtering with some adaptations. 
What do you think ?

**Comment by m-henderson** [comment]
That is a pretty good idea!
