### ISSUE TITLE
Return Current Count

### ISSUE THREAD

**Issue by m-henderson** [m-henderson/ProxySharp#2]
We need a method that returns the current count of the queue.

**Comment by Miiraak** [comment]
Hi @m-henderson ! 
A methode for the queue lenght or the position of the actually used proxy ?

**Comment by Miiraak** [comment]
After refexion, this method is not really useful, if the user want the nuber of proxies in queue he can use something like :

```cs
int lenght = Proxy.GetProxies().Count
```

And for the position... according the methodes, the used proxy is always at first index
