### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by m-henderson** [m-henderson/ProxySharp#9]
Tests need to be added to the project to keep from implementing breaking changes on accident.

**Comment by Miiraak** [comment]
For now i've dosen't check for test implementation but i've make a little dev app to test builded package methodes, if needed [ProxySharpTester](https://github.com/Miiraak/ProxySharpTester).

**Comment by Miiraak** [comment]
![image](https://github.com/user-attachments/assets/6db5c02b-01f1-46d6-95bb-c69c67ceee3a)
There is a probleme, idk why my solution 'proxySharp.tests' was not added to the push, will check it.... 
![image](https://github.com/user-attachments/assets/4af8726e-d12d-4de3-99fc-e9b986b5256d)

**Comment by Miiraak** [comment]
Okay, i've think i've found what wrong, im working on it 👍🏼 
I'll do pull this night or tomorrow
